# Introduction to NumPy

In [1]:
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
# upcasting
np.array([1.23, 2,3,4.3])

array([1.23, 2.  , 3.  , 4.3 ])

In [6]:
# set type
np.array([1,2,3,5], dtype='float32')

array([1., 2., 3., 5.], dtype=float32)

In [7]:
# multi-dimenstional arrays
np.array([range(i, i+4) for i in [2,4,8]])

array([[ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
np.array([range(i) for i in [2,4]])

/tmp/ipykernel_9515/1951621886.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([range(i) for i in [2,4]])


array([range(0, 2), range(0, 4)], dtype=object)

In [9]:
# arrays filled with zeros
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# 3x5 array filled with ones
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
# filled with default values
np.full((3,4), 42)

array([[42, 42, 42, 42],
       [42, 42, 42, 42],
       [42, 42, 42, 42]])

In [12]:
# 0-20 with step of 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# evenly sapeced
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
# random values between 0 and 1
np.random.random((2,2))

array([[0.30869961, 0.07403426],
       [0.45535475, 0.91051801]])

In [16]:
# random values with mean 0 and std 1
np.random.normal(0, 1, (2,2))

array([[-0.59685568, -0.08268032],
       [ 0.3575522 ,  0.55318279]])

In [18]:
# random integer in interval
np.random.randint(0,10, (2,2))

array([[2, 5],
       [2, 9]])

In [19]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# uninitialized integers
np.empty(3)

array([1., 1., 1.])

In [21]:
# seed for reproducibility
np.random.seed(42)

In [23]:
# one dimensional array
x = np.random.randint(10, size=6)
x

array([2, 6, 7, 4, 3, 7])

In [24]:
# two dimensional array
y = np.random.randint(10, size=(3,4))
y

array([[7, 2, 5, 4],
       [1, 7, 5, 1],
       [4, 0, 9, 5]])

In [26]:
# three dimensional array
z = np.random.randint(10, size=(3,4,5))
z

array([[[7, 7, 2, 0, 7],
        [2, 2, 0, 4, 9],
        [6, 9, 8, 6, 8],
        [7, 1, 0, 6, 6]],

       [[7, 4, 2, 7, 5],
        [2, 0, 2, 4, 2],
        [0, 4, 9, 6, 6],
        [8, 9, 9, 2, 6]],

       [[0, 3, 3, 4, 6],
        [6, 3, 6, 2, 5],
        [1, 9, 8, 4, 5],
        [3, 9, 6, 8, 6]]])

In [30]:
print("x ndim:", x.ndim)
print("x shape:", x.shape)
print("x size:", x.size)

x ndim: 1
x shape: (6,)
x size: 6


In [31]:
print("z ndim:", z.ndim)
print("z shape:", z.shape)
print("z size:", z.size)

z ndim: 3
z shape: (3, 4, 5)
z size: 60


In [35]:
x.dtype

dtype('int64')

In [36]:
print("x itemsize:", x.itemsize, "bytes")
print("x nbytes:", x.nbytes, "bytes")

x itemsize: 8 bytes
x nbytes: 48 bytes


In [37]:
y[0,0]

7

In [38]:
y[2,0]

4

In [39]:
# array slicing
# x[start:stop:step]

x[1:2:1]

array([6])

In [40]:
x = np.arange(10)

In [41]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
x[:5]

array([0, 1, 2, 3, 4])

In [43]:
x[3:5]

array([3, 4])

In [44]:
x[::4]

array([0, 4, 8])

In [46]:
x[1::3] # every other element starting at index 1

array([1, 4, 7])

In [47]:
x[::-1] # all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
x[4::-2] # reverse every other from index 4

array([4, 2, 0])

In [50]:
y

array([[7, 2, 5, 4],
       [1, 7, 5, 1],
       [4, 0, 9, 5]])

In [51]:
y[:2, :3] # two rows, three columns

array([[7, 2, 5],
       [1, 7, 5]])

In [52]:
y[:3, :1]

array([[7],
       [1],
       [4]])

In [53]:
y[1:, 2:]

array([[5, 1],
       [9, 5]])

In [54]:
y[:3, ::2] # every other column

array([[7, 5],
       [1, 5],
       [4, 9]])

In [55]:
y[::-1, ::-1]

array([[5, 9, 0, 4],
       [1, 5, 7, 1],
       [4, 5, 2, 7]])

In [56]:
y[:-1, :-1]

array([[7, 2, 5],
       [1, 7, 5]])

In [59]:
print(y[:,0]) # first column of y

[7 1 4]


In [61]:
print(y[0,:]) # first row of y

[7 2 5 4]


In [62]:
y_sub = y[:2, :2]

In [63]:
y_sub

array([[7, 2],
       [1, 7]])

In [64]:
# copy of an array
y_copy = y[:2, :2].copy()

In [65]:
y_copy

array([[7, 2],
       [1, 7]])

In [71]:
# reshaping

grid = np.arange(1, 5).reshape((2,2))
grid

array([[1, 2],
       [3, 4]])

In [72]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
x.reshape((1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [76]:
# row vector via newaxis
x[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [78]:
x.reshape((10,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [80]:
# concatenation
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [82]:
np.concatenate([x,y,z]) # cannot concatenate arrays of different dimensions

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 2 has 3 dimension(s)

In [83]:
grid = np.array([[1,2,3],
                 [4,5,6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [84]:
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [85]:
# vertically stack the arrays

x = np.array([1,2,3])

np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [89]:
# horizontally stack the arrays
y = np.array([[00],
              [00]])
np.hstack([y, grid])

array([[0, 1, 2, 3],
       [0, 4, 5, 6]])

In [90]:
# array splitting

x = [1,2,34,5,5,6]

x1 = np.split(x, [1,2])

In [91]:
x1

[array([1]), array([2]), array([34,  5,  5,  6])]